### ISSUE TITLE
AttributeError: /usr/lib/libdarknet.so: undefined symbol: load_network_custom

### ISSUE THREAD

**Issue by jeremy-rutman** [goktug97/PyYOLO#1]
I compiled darknet with the version at github as of 31 Jan 2020, which produced  a libdarknet.so (without actually setting any special flags in the makefile, but I tried adding `BUILD_SHARED_LIBS=on`
 in the Makefile in any case ; either way, I got a `AttributeError: /usr/lib/libdarknet.so: undefined symbol: load_network_custom`  upon trying to `import pyyolo`

**Comment by goktug97** [comment]
Are you using the https://github.com/AlexeyAB/darknet fork

**Comment by jeremy-rutman** [comment]
no i was using the original darknet fork

**Comment by goktug97** [comment]
It is written for the AlexeyAB fork
