### ISSUE TITLE
Google colab keeps on crashing while using pyyolo

### ISSUE THREAD

**Issue by ramgarg102** [goktug97/PyYOLO#3]
The modal keeps on crashing. I am using pyyolo to detect objects in a video. But every time after two detections, the kernel crashes and restarts.

Timestamp | Level | Message
-- | -- | --
Jun 11, 2020, 6:39:29 PM | WARNING | WARNING:root:kernel 1c954a2c-3ad4-449e-b204-44f85e85de9a restarted
Jun 11, 2020, 6:39:29 PM | INFO | KernelRestarter: restarting kernel (1/5), keep random ports
Jun 11, 2020, 6:39:16 PM | WARNING | Done! Loaded 162 layers from weights-file
Jun 11, 2020, 6:39:15 PM | WARNING | Try to load weights: /mydrive/backup/yolov4_custom2_final.weights
Jun 11, 2020, 6:39:15 PM | WARNING | nms_kind: greedynms (1), beta = 0.600000
Jun 11, 2020, 6:39:15 PM | WARNING | nms_kind: greedynms (1), beta = 0.600000
Jun 11, 2020, 6:39:15 PM | WARNING | nms_kind: greedynms (1), beta = 0.600000
Jun 11, 2020, 6:39:15 PM | WARNING | mini_batch = 1, batch = 1, time_steps = 1, train = 0
Jun 11, 2020, 6:39:15 PM | WARNING | net.optimized_memory = 0
Jun 11, 2020, 6:39:15 PM | WARNING | Try to load cfg: /content/darknet/cfg/yolov4_custom2.cfg, weights: /mydrive/backup/yolov4_custom2_final.weights, clear = 0
Jun 11, 2020, 6:39:15 PM | WARNING | Loading weights from /mydrive/backup/yolov4_custom2_final.weights...
Jun 11, 2020, 6:39:15 PM | WARNING | Allocate additional workspace_size = 52.43 MB
Jun 11, 2020, 6:39:15 PM | WARNING | avg_outputs = 489778
Jun 11, 2020, 6:39:15 PM | WARNING | Total BFLOPS 59.563
Jun 11, 2020, 6:39:15 PM | WARNING | [yolo] params: iou loss: ciou (4), iou_norm: 0.07, cls_norm: 1.00, scale_x_y: 1.05

![Screenshot (38)](https://user-images.githubusercontent.com/47526387/84424903-5c04f500-ac3e-11ea-9b88-dd4f17264189.png)

**Comment by goktug97** [comment]
It might be a google colab issue. Did you try to run it on your local machine because I haven't tested it using Yolov4? Can you ensure you can make it work locally?

**Comment by ramgarg102** [comment]
I asked the same to folks at colab. They asked me to ask you guys. I can't
do it on a local machine because my GPU does not support CUDA. It's an
Intel GPU.

**Comment by goktug97** [comment]
You actually don't need a GPU to run Darknet. You can compile Darknet without GPU support. For example in Linux,
https://github.com/AlexeyAB/darknet/blob/0a42f8d6144a0a388b1da238fe078af981d07be0/Makefile#L1-L3
if these lines are `1` replace them with `0` and then recompile.

**Comment by ramgarg102** [comment]
Is pyyolo only compatible with yolov3 or works also for yolov4?

**Comment by goktug97** [comment]
It just reads weights and configuration, it should work with YOLOv4 too.

**Comment by ramgarg102** [comment]
It's just an observation. I tried it with both yolov3 and yolov4 weights
and cfg. The pyyolo works just fine with yolov3 but with yolov4, the
session crashes even before the detection starts. I think it needs to be
tweaked to work with yolov4 weights.

Anyway, it is an amazing tool and keep up.

**Comment by goktug97** [comment]
Can you try with the recent update? Updated it to work with the recent darknet repo, tested with the Yolov4 and it works for me.

**Comment by ramgarg102** [comment]
It's working perfectly now with yolov4 weights also.

Thanks for the update.
