### ISSUE TITLE
is this working with yolov4 as well?

### ISSUE THREAD

**Issue by samux87** [goktug97/PyYOLO#4]

**Comment by goktug97** [comment]
It seems currently it doesn’t 
https://github.com/goktug97/PyYOLO/issues/3

**Comment by goktug97** [comment]
It seems the detection structure is changed. Updated the repo and it should work with Yolov4 now. I tested it with yolov4.cfg and yolov4.weights.

EDIT: It works with YOLOv4 https://github.com/goktug97/PyYOLO/issues/3

**Comment by samux87** [comment]
❤ 
I will test it out. Thank you so much.
S.

**Comment by mmartial** [comment]
Just tested it out with Yolo v4 and pointed people to use your repo 
https://github.com/datamachines/cuda_tensorflow_opencv#641-using-pyyolo

Thanks for updating this wrapper :)

**Comment by goktug97** [comment]
> Just tested it out with Yolo v4 and pointed people to use your repo
> https://github.com/datamachines/cuda_tensorflow_opencv#641-using-pyyolo
> 
> Thanks for updating this wrapper :)

I am glad that it is working
