### ISSUE TITLE
updated yolov4 repo

### ISSUE THREAD

**Issue by lars-ek** [goktug97/PyYOLO#6]
Hi!

I compiled darknet some days ago to get the dll and everything worked fine.

But something was changed by Alexey... when I compile the dll with the latest version (on Linux AND Windows), the PyYOLO code will just hang and stops working without an error-message.

Can this be a compatibility issue?

Thank you.

**Comment by goktug97** [comment]
Yes, it seems new attributes are added to DETECTION structure. I updated the repo, it works now. Beware that I only made this repo to work with Linux.

Thank you for notifying me!
